/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoginMain;

import Connector.DbConnection;
import com.jfoenix.controls.JFXButton;
import com.jfoenix.controls.JFXTextField;
import java.net.URL;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.ResourceBundle;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import no.vianett.sms.Sms;
import no.vianett.sms.SmsEvent;
import no.vianett.sms.SmsEventListener;
import no.vianett.sms.component.SmsTransceiver;
import no.vianett.sms.event.SmsDeliveredEvent;
import no.vianett.sms.event.SmsDeliveryFailedEvent;
import no.vianett.sms.event.SmsSendingFailedEvent;
import no.vianett.sms.log.SmsScreenLogger;

/**
 * FXML Controller class
 *
 * @author llb
 */
public class RegController implements Initializable {

    @FXML
    private JFXTextField txtfname;
    @FXML
    private JFXTextField txtlname;
    @FXML
    private JFXTextField txtmobile;
    @FXML
    private JFXButton reg;
    @FXML
    private JFXButton brnclear;

       @FXML
    void reg(ActionEvent event) throws SQLException {
        Connector.DbConnection con=new DbConnection();
             
             Connection conn=con.connect();
             
              Statement st=conn.createStatement();
               DateFormat dateFormat = new SimpleDateFormat("MMM dd,yyyy");
               Date date = new Date();
              String sql ="insert into members(Member_Id,Frist_Name,Last_Name,Date) values("+txtmobile.getText()+",'"+txtfname.getText()+"','"+txtlname.getText()+"','"+dateFormat.format(date)+"')";
              st.executeUpdate(sql);
              String number=txtmobile.getText();
             // SmsSender ss=new SmsSender("1234","Thanks for choosing us now you are a customer of lion pizza","0094"+number);
              
             
       
    }
    @Override
    public void initialize(URL url, ResourceBundle rb) {
        
    }    

    @FXML
    private void clear(ActionEvent event) {
        txtfname.setText("");
        txtlname.setText("");
        txtmobile.setText("");
    }
    
    public void settexte(int mob)
    {
        this.txtmobile.setText(Integer.toString(mob));
    }
    
}
class SmsSender implements SmsEventListener
{
    private SmsTransceiver transceiver = null;
    private Object link = null; // Just to keep this object alive.
    private int counter = 0;
 
    public SmsSender(String sender,String message,String number)
    {
        this.link = this; // Keeps this object alive.
        this.transceiver = SmsTransceiver.getInstance(); // Get the transceiver object.
 
        // Initialize transceiver.
        String smsHost = "cpa.vianett.no";
        String smsPort = "31337";
        String smsUsername = "madunikamerani@gmail.com";
        String smsPassword = "kw6xi";
        this.transceiver.initialize( smsHost, Integer.parseInt( smsPort ), smsUsername, smsPassword, new SmsScreenLogger() );
 
        this.transceiver.addSmsEventListener(this); // Registrer this class as listener for SMS events.
 
        // Send message
        Sms sms = new Sms();
        sms.setId( ++this.counter );
        sms.setReplyPath( 100 );
        sms.setSender( sender ); // Set the sender number.
        sms.setMessage( message);
        sms.setRecipient( number); // The recipients phone number.
 
        this.transceiver.send( sms );
    }
 
    // Just make new instance of this class.
    
 
    /**
    * Listener.
    *
    * @param event a <code>no.vianett.sms.SmsEvent</code>
    */
    public void eventHappened( SmsEvent event )
    {
        if( event instanceof SmsDeliveredEvent )
        {
            System.out.println( "Sms delivered." );
            System.out.println( "Refno : " + event.getReferenceId() );
            System.out.println( "Sms generated by : " + event.getSource().getClass() );
        }
        else if( event instanceof SmsSendingFailedEvent )
        {
            System.out.println( "Sms sending failed." );
            System.out.println( "Refno : " + event.getReferenceId() );
            System.out.println( "Return code : " + ( ( SmsSendingFailedEvent ) event ).getReturnCode() );
            System.out.println( "Sms generated by : " + event.getSource().getClass() );
        }
        else if( event instanceof SmsDeliveryFailedEvent )
        {
            System.out.println( "Sms delivery failed." );
            System.out.println( "Refno : " + event.getReferenceId() );
            System.out.println( "Error code : " + ( ( SmsDeliveryFailedEvent ) event ).getErrorCode() );
            System.out.println( "Sms generated by : " + event.getSource().getClass() );
        }
    }
 
}
